### ISSUE TITLE
При нажатии на orders ошибка 500

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/ic-dev#17]
![2014-12-14 20 30 39](https://cloud.githubusercontent.com/assets/9354450/5428743/24af15d2-83d0-11e4-9d94-1149ef25d335.png)
![2014-12-14 20 30 46](https://cloud.githubusercontent.com/assets/9354450/5428744/26936d62-83d0-11e4-89bf-f22bc6bce81f.png)

**Comment by schaman** [comment]
fixed
