### ISSUE TITLE
При нажатии на продукт ошибка 500

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/ic-dev#18]
![2014-12-14 20 31 46](https://cloud.githubusercontent.com/assets/9354450/5428745/45cbc580-83d0-11e4-9316-dd549b6cf678.png)
![2014-12-14 20 31 49](https://cloud.githubusercontent.com/assets/9354450/5428746/478dcda0-83d0-11e4-9f93-e0cc546474e2.png)

**Comment by schaman** [comment]
fixed
