### ISSUE TITLE
Данные не корректно отображаются

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/ic-dev#21]
[человек](http://ic.icoach.io/admin/q/customer/22732) заказал продукт [best](http://ic.icoach.io/admin/product/10)

и данные не отображаются

![2014-12-16 20 31 55](https://cloud.githubusercontent.com/assets/9354450/5460416/d6c9519a-8562-11e4-8dd0-bb373c57299a.png)
![2014-12-16 20 32 00](https://cloud.githubusercontent.com/assets/9354450/5460419/d9bf50fc-8562-11e4-84d0-d1d4ea969cbd.png)

**Comment by schaman** [comment]
fixed
