### ISSUE TITLE
 Починить мх

### ISSUE THREAD

**Issue by antariys081** [schaman/ic-dev#29]
Хочу сама отсылать письма, когда это нужно.
Что не работает:
1. Не могу открыть любое письмо в мх ( Нажимаю на название письма, открывается пустой экран)
2. Когда создаю письмо( Нажала - создать новое письмо, наполняю его, потом нажимаю кнопку сохранить - то же самое, показывается пустой экран, а письмо сохраняется в папке - неактивные письма. Активировать его не могу - когда нажимаю на заголовок - пустой экран)
У Кирилла все работает, у меня нет.

Почини пожалуйста.

**Comment by schaman** [comment]
![mkh_slomalsya](https://cloud.githubusercontent.com/assets/1928852/7219378/27827d34-e6a5-11e4-934c-e135a4f55d10.png)

**Comment by schaman** [comment]
fixed
