### ISSUE TITLE
Календарь работает некорректно

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/ic-dev#30]
У меня на сегодня (и на весь июль) запланированы звонки

Пруф: 

![2015-07-01 13 39 19](https://cloud.githubusercontent.com/assets/9354450/8453640/c12bee04-1ff6-11e5-8076-7510130e6274.png)

А в календаре все пропало!...

![2015-07-01 13 39 24](https://cloud.githubusercontent.com/assets/9354450/8453649/cade9208-1ff6-11e5-8b13-47fff6aab102.png)

Паника!

**Comment by schaman** [comment]
fixed
