### ISSUE TITLE
Что значит параметр updated?

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/ic-dev#8]
вот тут: http://ic.icoach.io/admin/customer/

Я думал, это дата заказа, тогда почему клиенты идут не по порядку?

![2014-12-01 0 07 37](https://cloud.githubusercontent.com/assets/9354450/5239785/66d3b888-78ee-11e4-8a7f-375cfa6b3c0f.png)

**Comment by schaman** [comment]
Поле спрятано
